apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2team4-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-deployment
  template:
    metadata:
      labels:
        app: react-deployment
    spec:
      containers:
      - image: project2team4/react:latest
        initialDelaySeconds: 5
        imagePullPolicy: Always
        name: react
        ports: 
        - containerPort: 3000
        livenessProbe:
            httpGet:
                path: /
                port: 3000
                httpHeaders:
                  - name: Custom-Header
                    value: Awesome
                
                  
        readinessProbe:
            httpGet:
              path: /
              port: 3000
              
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-deployment
  ports:
  - port: 3000
    targetPort: 3000
    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-ingress-data
  labels:
    name: react-ingress
spec:
  defaultBackend:
    service:
      name: react-service
      port: 
        number: 3000
