
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2team4-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-deployment
  template:
    metadata:
      labels:
        app: react-deployment
    spec:
      containers:
      - image: project2team4/react:%TAG%
        env:
          - name: REACT_APP_JAVA_URL
            value:  http://34.133.185.13:8080
          - name: LOKI_URL
            value: loki://$(LOKI_SERVICE_HOST):$(LOKI_SERVICE_PORT)
        imagePullPolicy: Always
        name: react
        ports: 
        - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-service
  name: react
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: "3030"
      port: 3030
      targetPort: 3030
  selector:
    app: react-deployment
    